{{- $tier := "apps" -}}
{{- range $k, $v := $.Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $tier }}-{{ $.Values.general.product }}-{{ $k }}
  labels:
    environment: {{ $.Values.general.environment }}
    product: {{ $.Values.general.product }}
    app: {{ $tier }}-{{ $.Values.general.product }}-{{ $k }}
spec:
  replicas: {{ $v.replicaCount }}
  selector:
    matchLabels:
      app: {{ $tier }}-{{ $.Values.general.product }}-{{ $k }}
  template:
    spec:
      containers:
        - name: {{ $tier }}-{{ $k }}-cntr
          image: "{{ $.Values.image.registry }}{{ $v.image.repository }}:{{ $v.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: 'config-apps-{{ $.Values.general.product }}'
          env:
          - name: PLATFORM_VERSION
            value: "{{ $.Chart.AppVersion }}"
          ports:
          - containerPort: {{ $v.port }}
            name: {{ $.Values.general.product  }}-port-cntr
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ $.Values.general.product  }}-port-cntr
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              {{- if $v.resources.requests.memory }}
              memory: {{ $v.resources.requests.memory }}
              {{- end }}
              {{- if $v.resources.requests.cpu }}
              cpu: {{ $v.resources.requests.cpu }}
              {{- end }}
          volumeMounts:
            - name: application-config 
              mountPath: /config 
              readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: 'config-apps-{{ $.Values.general.product }}'
          items:
          - key: services.properties
            path: services.properties
      restartPolicy: Always
---
{{- end }}
