{{- $tier := "secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tier }}-{{ $.Values.general.product }}
type: Opaque
data:
  MONGODB_ADMIN_PWD: {{ $.Values.database.mongodb.rootPwd | b64enc }}
  MONGODB_USER_PWD: {{ $.Values.database.mongodb.userPwd | b64enc }}